# Generated by Django 4.2.30 on 2026-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_alter_property_options_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='India', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='country_code',
            field=models.CharField(default='IN', max_length=10),
        ),
    ]
